/**
 * Cinematography preview thumbnails.
 * Conventions and prompts: public/assets/cinematography-previews/prompts.json
 */
const PREVIEW_BY_SECTION_ABBR: Record<string, string> = {
  'shotTypes:ECU': '/assets/cinematography-previews/shot-types/ecu.jpg',
  'shotTypes:CU': '/assets/cinematography-previews/shot-types/cu.jpg',
  'shotTypes:MCU': '/assets/cinematography-previews/shot-types/mcu.jpg',
  'shotTypes:MS': '/assets/cinematography-previews/shot-types/ms.jpg',
  'shotTypes:MLS': '/assets/cinematography-previews/shot-types/mls.jpg',
  'shotTypes:Cowboy': '/assets/cinematography-previews/shot-types/cowboy.jpg',
  'shotTypes:LS/WS': '/assets/cinematography-previews/shot-types/ls-ws.jpg',
  'shotTypes:ELS': '/assets/cinematography-previews/shot-types/els.jpg',
  'angles:Eye-Level': '/assets/cinematography-previews/angles/eye-level.jpg',
  'angles:Low Angle': '/assets/cinematography-previews/angles/low-angle.jpg',
  'angles:High Angle': '/assets/cinematography-previews/angles/high-angle.jpg',
  'angles:Dutch': '/assets/cinematography-previews/angles/dutch.jpg',
  'angles:Overhead': '/assets/cinematography-previews/angles/overhead.jpg',
  "angles:Worm's Eye": '/assets/cinematography-previews/angles/worms-eye.jpg',
  'angles:OTS': '/assets/cinematography-previews/angles/ots.jpg',
  'angles:POV': '/assets/cinematography-previews/angles/pov.jpg',
  'composition:Rule of ⅓': '/assets/cinematography-previews/composition/rule-of-thirds.jpg',
  'composition:Centered': '/assets/cinematography-previews/composition/centered.jpg',
  'composition:Asymm.': '/assets/cinematography-previews/composition/asymmetrical.jpg',
  'composition:Symm.': '/assets/cinematography-previews/composition/symmetrical.jpg',
  'composition:Lead Lines': '/assets/cinematography-previews/composition/leading-lines.jpg',
  'composition:Frame²': '/assets/cinematography-previews/composition/frame-within-frame.jpg',
  'composition:Neg Space': '/assets/cinematography-previews/composition/negative-space.jpg',
  'composition:φ Grid': '/assets/cinematography-previews/composition/phi-grid.jpg',
  'composition:FMB': '/assets/cinematography-previews/composition/foreground-mid-back.jpg',
  'composition:Diagonal': '/assets/cinematography-previews/composition/diagonal.jpg',
  'composition:Tight': '/assets/cinematography-previews/composition/tight.jpg',
  'composition:Loose': '/assets/cinematography-previews/composition/loose.jpg',
  'composition:Overlap': '/assets/cinematography-previews/composition/overlap.jpg',
  'composition:S-Curve': '/assets/cinematography-previews/composition/s-curve.jpg',
  'composition:△ Comp': '/assets/cinematography-previews/composition/pyramid-triangular.jpg',
  'composition:○ Comp': '/assets/cinematography-previews/composition/circular.jpg',
  'lighting:3-Point': '/assets/cinematography-previews/lighting/3-point.jpg',
  'lighting:High-Key': '/assets/cinematography-previews/lighting/high-key.jpg',
  'lighting:Low-Key': '/assets/cinematography-previews/lighting/low-key.jpg',
  'lighting:Side': '/assets/cinematography-previews/lighting/side.jpg',
  'lighting:Backlit': '/assets/cinematography-previews/lighting/backlit.jpg',
  'lighting:Rim': '/assets/cinematography-previews/lighting/rim.jpg',
  'lighting:Golden Hr': '/assets/cinematography-previews/lighting/golden-hr.jpg',
  'lighting:Blue Hr': '/assets/cinematography-previews/lighting/blue-hr.jpg',
  'lighting:Practical': '/assets/cinematography-previews/lighting/practical.jpg',
  'lighting:Gels': '/assets/cinematography-previews/lighting/gels.jpg',
  'lighting:Hard': '/assets/cinematography-previews/lighting/hard.jpg',
  'lighting:Soft': '/assets/cinematography-previews/lighting/soft.jpg',
  'movements:POV Track': '/assets/cinematography-previews/movements/pov-track.jpg',
  'movements:Dolly Zoom': '/assets/cinematography-previews/movements/dolly-zoom.jpg',
  'movements:Pan': '/assets/cinematography-previews/movements/pan.jpg',
  'movements:Tilt': '/assets/cinematography-previews/movements/tilt.jpg',
  'movements:Orbit': '/assets/cinematography-previews/movements/orbit.jpg',
  'movements:Handheld': '/assets/cinematography-previews/movements/handheld.jpg',
  'movements:Steadicam': '/assets/cinematography-previews/movements/steadicam.jpg',
  'movements:Zoom': '/assets/cinematography-previews/movements/zoom.jpg',
  'movements:Static': '/assets/cinematography-previews/movements/static.jpg',
  'movements:Push In': '/assets/cinematography-previews/movements/push-in.jpg',
  'movements:Whip Pan': '/assets/cinematography-previews/movements/whip-pan.jpg',
  'movements:Crane': '/assets/cinematography-previews/movements/crane.jpg',
  'movements:Drone': '/assets/cinematography-previews/movements/drone.jpg',
  'atmosphere:Fog': '/assets/cinematography-previews/atmosphere/fog.jpg',
  'atmosphere:Rain': '/assets/cinematography-previews/atmosphere/rain.jpg',
  'atmosphere:God Rays': '/assets/cinematography-previews/atmosphere/god-rays.jpg',
  'atmosphere:Dust': '/assets/cinematography-previews/atmosphere/dust.jpg',
  'atmosphere:Haze': '/assets/cinematography-previews/atmosphere/haze.jpg',
  'atmosphere:Smoke': '/assets/cinematography-previews/atmosphere/smoke.jpg',
  'atmosphere:Snow': '/assets/cinematography-previews/atmosphere/snow.jpg',
  'atmosphere:Heat': '/assets/cinematography-previews/atmosphere/heat.jpg',
};

/** Preview thumbnail URL for a camera/lighting chip, if an asset exists. */
export function getCameraLightingPreviewSrc(sectionKey: string, abbr: string): string | null {
  return PREVIEW_BY_SECTION_ABBR[`${sectionKey}:${abbr}`] ?? null;
}
