import type { CameraItem } from '@/camera/camera-lighting-bundle';

export interface SFXSection {
  id: string;
  title: string;
  icon: string;
  items: CameraItem[];
}

export const sfxAtmosphere: CameraItem[] = [
  { abbr: 'Fog', name: 'Fog / Mist', desc: 'Low visibility — mysterious depth and ethereal mood', params: [{ key: 'density', label: 'Density', type: 'select', defaultValue: 'Medium', options: [{ label: 'Light', value: 'Light' }, { label: 'Medium', value: 'Medium' }, { label: 'Dense', value: 'Dense' }] }, { key: 'colorTemp', label: 'Color Temp', type: 'select', defaultValue: 'Neutral', options: [{ label: 'Warm', value: 'Warm' }, { label: 'Neutral', value: 'Neutral' }, { label: 'Cool', value: 'Cool' }] }] },
  { abbr: 'Rain', name: 'Rain', desc: 'Wet surfaces and falling drops — tension, melancholy or romance', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Light', value: 'Light' }, { label: 'Medium', value: 'Medium' }, { label: 'Heavy', value: 'Heavy' }] }] },
  { abbr: 'God Rays', name: 'God Rays / Vol. Light', desc: 'Shafts of light through haze — dramatic and sacred atmosphere', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Subtle', value: 'Subtle' }, { label: 'Medium', value: 'Medium' }, { label: 'Strong', value: 'Strong' }] }] },
  { abbr: 'Dust', name: 'Dust / Particles', desc: 'Floating motes in the air — age, decay or dry heat', params: [{ key: 'density', label: 'Density', type: 'select', defaultValue: 'Medium', options: [{ label: 'Light', value: 'Light' }, { label: 'Medium', value: 'Medium' }, { label: 'Heavy', value: 'Heavy' }] }] },
  { abbr: 'Haze', name: 'Haze / Atmos. Haze', desc: 'Soft horizon diffusion — distance and scale in outdoor shots', params: [{ key: 'density', label: 'Density', type: 'select', defaultValue: 'Medium', options: [{ label: 'Light', value: 'Light' }, { label: 'Medium', value: 'Medium' }, { label: 'Dense', value: 'Dense' }] }] },
  { abbr: 'Smoke', name: 'Smoke', desc: 'Billowing or drifting smoke — danger, mystery or aftermath', params: [{ key: 'density', label: 'Density', type: 'select', defaultValue: 'Medium', options: [{ label: 'Light', value: 'Light' }, { label: 'Medium', value: 'Medium' }, { label: 'Heavy', value: 'Heavy' }] }, { key: 'movement', label: 'Movement', type: 'select', defaultValue: 'Normal', options: [{ label: 'Still', value: 'Still' }, { label: 'Swirling', value: 'Swirling' }, { label: 'Turbulent', value: 'Turbulent' }] }] },
  { abbr: 'Snow', name: 'Snow / Frost', desc: 'Falling flakes or ice — isolation, purity or cold threat', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Light', value: 'Light' }, { label: 'Medium', value: 'Medium' }, { label: 'Heavy', value: 'Heavy' }] }] },
  { abbr: 'Heat', name: 'Heat Shimmer', desc: 'Shimmering distortion off hot surfaces — oppressive heat', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Subtle', value: 'Subtle' }, { label: 'Medium', value: 'Medium' }, { label: 'Strong', value: 'Strong' }] }] },
];

export const sfxWeather: CameraItem[] = [
  { abbr: 'Heavy Rain', name: 'Heavy Rain Storm', desc: 'Intense downpour with wind and thunder — chaos and tension', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Severe', options: [{ label: 'Moderate', value: 'Moderate' }, { label: 'Severe', value: 'Severe' }, { label: 'Extreme', value: 'Extreme' }] }] },
  { abbr: 'Snowfall', name: 'Gentle Snow Fall', desc: 'Silent flakes drifting down — isolation, peace or melancholy', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Light', value: 'Light' }, { label: 'Medium', value: 'Medium' }, { label: 'Heavy', value: 'Heavy' }] }] },
  { abbr: 'Thick Fog', name: 'Thick Fog / Mist', desc: 'Dense ground-level fog — mystery, horror or ethereal beauty', params: [{ key: 'density', label: 'Density', type: 'select', defaultValue: 'Dense', options: [{ label: 'Medium', value: 'Medium' }, { label: 'Dense', value: 'Dense' }, { label: 'Impenetrable', value: 'Impenetrable' }] }] },
  { abbr: 'Sunny Day', name: 'Bright Sunny Daylight', desc: 'Clear blue sky with hard sunlight — open, honest, warm', params: [{ key: 'colorTemp', label: 'Color Temp', type: 'select', defaultValue: 'Warm', options: [{ label: 'Warm', value: 'Warm' }, { label: 'Neutral', value: 'Neutral' }, { label: 'Cool', value: 'Cool' }] }] },
  { abbr: 'Thunder', name: 'Dramatic Thunderstorm', desc: 'Lightning, rolling clouds, shifting light — epic foreboding', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Severe', options: [{ label: 'Mild', value: 'Mild' }, { label: 'Medium', value: 'Medium' }, { label: 'Severe', value: 'Severe' }] }] },
  { abbr: 'Wind', name: 'Wind Blown Elements', desc: 'Leaves, dust, debris pushed by strong wind — dynamic and restless', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Light', value: 'Light' }, { label: 'Medium', value: 'Medium' }, { label: 'Strong', value: 'Strong' }] }] },
  { abbr: 'Desert Haze', name: 'Dry Desert Heat Haze', desc: 'Shimmering heat distortion over arid landscape — oppressive and vast', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Subtle', value: 'Subtle' }, { label: 'Medium', value: 'Medium' }, { label: 'Strong', value: 'Strong' }] }] },
  { abbr: 'Neon Wet', name: 'Urban Neon Reflections', desc: 'Rain-slicked streets reflecting colorful neon signs — cyberpunk mood', params: [{ key: 'tone', label: 'Tone', type: 'select', defaultValue: 'Cool', options: [{ label: 'Warm', value: 'Warm' }, { label: 'Cool', value: 'Cool' }, { label: 'Mixed', value: 'Mixed' }] }] },
  { abbr: 'Underwater', name: 'Underwater Caustics', desc: 'Dappled light patterns and suspended particles — submerged, dreamlike', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Subtle', value: 'Subtle' }, { label: 'Medium', value: 'Medium' }, { label: 'Strong', value: 'Strong' }] }] },
];

export const sfxParticle: CameraItem[] = [
  { abbr: 'Embers', name: 'Floating Embers / Sparks', desc: 'Glowing orange embers drifting upward — warmth, danger or aftermath', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Few', value: 'Few' }, { label: 'Medium', value: 'Medium' }, { label: 'Many', value: 'Many' }] }, { key: 'speed', label: 'Speed', type: 'select', defaultValue: 'Normal', options: [{ label: 'Slow', value: 'Slow' }, { label: 'Normal', value: 'Normal' }, { label: 'Fast', value: 'Fast' }] }] },
  { abbr: 'Magic Dust', name: 'Sparkling Magic Particles', desc: 'Twinkling shimmering motes of light — enchantment, wonder or fantasy', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Subtle', value: 'Subtle' }, { label: 'Medium', value: 'Medium' }, { label: 'Dense', value: 'Dense' }] }, { key: 'speed', label: 'Speed', type: 'select', defaultValue: 'Normal', options: [{ label: 'Slow', value: 'Slow' }, { label: 'Normal', value: 'Normal' }, { label: 'Fast', value: 'Fast' }] }] },
  { abbr: 'Vol Rays', name: 'Volumetric God Rays', desc: 'Shafts of light piercing through haze — sacred, hopeful, dramatic', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Subtle', value: 'Subtle' }, { label: 'Medium', value: 'Medium' }, { label: 'Strong', value: 'Strong' }] }] },
  { abbr: 'Flare', name: 'Lens Flares', desc: 'Bright highlights streaking across the frame — cinematic flare', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Subtle', value: 'Subtle' }, { label: 'Medium', value: 'Medium' }, { label: 'Strong', value: 'Strong' }] }, { key: 'colorTemp', label: 'Color Temp', type: 'select', defaultValue: 'Warm', options: [{ label: 'Warm', value: 'Warm' }, { label: 'Neutral', value: 'Neutral' }, { label: 'Cool', value: 'Cool' }] }] },
  { abbr: 'Holo', name: 'Holographic Projections', desc: 'Glowing digital overlays and transparent data displays — sci-fi', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Subtle', value: 'Subtle' }, { label: 'Medium', value: 'Medium' }, { label: 'Bright', value: 'Bright' }] }, { key: 'color', label: 'Color', type: 'select', defaultValue: 'Cyan', options: [{ label: 'Cyan', value: 'Cyan' }, { label: 'Blue', value: 'Blue' }, { label: 'Green', value: 'Green' }, { label: 'Amber', value: 'Amber' }] }] },
  { abbr: 'Steam', name: 'Smoke / Steam Swirls', desc: 'Billowing clouds of vapor — industrial, mysterious or atmospheric', params: [{ key: 'density', label: 'Density', type: 'select', defaultValue: 'Medium', options: [{ label: 'Light', value: 'Light' }, { label: 'Medium', value: 'Medium' }, { label: 'Heavy', value: 'Heavy' }] }, { key: 'movement', label: 'Movement', type: 'select', defaultValue: 'Normal', options: [{ label: 'Still', value: 'Still' }, { label: 'Normal', value: 'Normal' }, { label: 'Turbulent', value: 'Turbulent' }] }] },
  { abbr: 'Splash', name: 'Water Splash / Droplets', desc: 'Suspended droplets catching light — freshness, impact or underwater', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Few', value: 'Few' }, { label: 'Medium', value: 'Medium' }, { label: 'Many', value: 'Many' }] }] },
  { abbr: 'Debris', name: 'Explosive Debris', desc: 'Fragments and particles from an impact — chaos, violence, destruction', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Light', value: 'Light' }, { label: 'Medium', value: 'Medium' }, { label: 'Heavy', value: 'Heavy' }] }] },
  { abbr: 'Energy Aura', name: 'Glowing Energy Aura', desc: 'Luminous halo around the subject — power, magic or transformation', params: [{ key: 'intensity', label: 'Intensity', type: 'select', defaultValue: 'Medium', options: [{ label: 'Subtle', value: 'Subtle' }, { label: 'Medium', value: 'Medium' }, { label: 'Bright', value: 'Bright' }] }, { key: 'color', label: 'Color', type: 'select', defaultValue: 'Blue', options: [{ label: 'Blue', value: 'Blue' }, { label: 'Green', value: 'Green' }, { label: 'Pink', value: 'Pink' }, { label: 'Purple', value: 'Purple' }, { label: 'Orange', value: 'Orange' }] }] },
  { abbr: 'Butterfly', name: 'Butterfly Swarm Flutter', desc: 'Fluttering wings filling the frame — beauty, transformation or chaos', params: [{ key: 'density', label: 'Density', type: 'select', defaultValue: 'Medium', options: [{ label: 'Few', value: 'Few' }, { label: 'Medium', value: 'Medium' }, { label: 'Swarm', value: 'Swarm' }] }, { key: 'speed', label: 'Speed', type: 'select', defaultValue: 'Normal', options: [{ label: 'Slow', value: 'Slow' }, { label: 'Normal', value: 'Normal' }, { label: 'Frantic', value: 'Frantic' }] }] },
];

export const sfxSections: Record<string, CameraItem[]> = {
  atmosphere: sfxAtmosphere,
  weather: sfxWeather,
  particleFx: sfxParticle,
};

export const sfxSectionMeta: Record<string, SFXSection> = {
  atmosphere: { id: 'sfx-atmosphere', title: 'Atmospheric Effects', icon: 'fa-cloud-rain', items: sfxAtmosphere },
  weather: { id: 'sfx-weather', title: 'Weather & Environment', icon: 'fa-cloud-sun', items: sfxWeather },
  particleFx: { id: 'sfx-particle', title: 'Particle Effects', icon: 'fa-sparkles', items: sfxParticle },
};
